const className = [
  'Founders',
  'unixcórnios',
  'unforgitables',
  'bashtards',
  'vi_kings',
  'boolegans',
  'javangers',
  'roothless',
  'sshavages',
  'karbashians',
  'intellijunkies',
  'enuminatti',
  'boolefighters',
  'hexallents',
  'haltistas',
  'popstars',
  'stormrooters',
  'sshardinhas',
  'variachis',
  'hashtronauts',
  'ninjars',
  'invictus',
  'asciimós',
  'tropadelete',
  'javapeños',
  'mainiacs',
  'murlogs',
  '27 name?',
  'codezillas',
  'whiledlings',
  'whiledcards',
  'stringrays',
  'thunderstructs',
  'stringteasers',
  'vimdiesels',
  'cannabits',
  'splicegirls',
  'paparasciis',
  'hackstreetboys',
  'apiores',
  'rhashtafaris',
  'hackstreetboys',
  'preditors',
  'ramsters',
]

export default className;